name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U app -d app_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql+psycopg2://app:secret@localhost:5432/app_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        run: |
          black --check .
          ruff check .

      - name: Run tests
        run: |
          pytest -q

      - name: Start app (uvicorn) in background
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
          
          for i in $(seq 1 40); do
            if curl -sSf http://127.0.0.1:8000/health >/dev/null 2>&1; then
              echo "app is up"
              break
            fi
            sleep 1
          done
          
          tail -n +1 uvicorn.log || true

      - name: Install Gauge
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          echo "$HOME/.gauge/bin" >> $GITHUB_PATH
          gauge version

      - name: Run Gauge specs
        run: |
          gauge run specs